[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
static-opti = { path = ".." }
# Small and performant allocator
mimalloc = { version = "0.1", default-features = false }
# CLI utils
clap = { version = "3.2.15", features = ["derive"] }
